server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        messages-in-0:
          consumer:
            partitioned: true
          destination: messages
          group: messages_group
          content-type: text/plain
      kafka:
        binder:
          brokers: localhost:9093
